# Generated by Django 5.2.2 on 2025-12-18 11:30

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CertificateRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_id', models.CharField(max_length=20)),
                ('user_name', models.CharField(max_length=100)),
                ('certificate_name', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_remarks', models.TextField(blank=True, null=True)),
                ('blockchain_hash', models.CharField(blank=True, max_length=200, null=True)),
                ('certificate_file', models.FileField(blank=True, null=True, upload_to='certificates/%Y/%m/%d/')),
                ('reject_reason', models.CharField(blank=True, choices=[('invalid_certificate', 'Invalid Certificate'), ('document_not_clear', 'Document Not Clear'), ('information_mismatch', 'Information Mismatch'), ('certificate_expired', 'Certificate Expired'), ('duplicate_request', 'Duplicate Request'), ('other', 'Other Reason')], max_length=50, null=True)),
                ('reject_details', models.TextField(blank=True, null=True)),
                ('request_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('accepted_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'CertificateRequest',
                'ordering': ['-request_date'],
            },
        ),
    ]
